import {
  Activity,
  AlertTriangle,
  Archive,
  ArchiveRestore,
  ArrowDownToLine,
  ArrowUpToLine,
  Badge,
  BarChart,
  BookOpen,
  Box,
  Brain,
  BrainCircuit,
  Briefcase,
  Bug,
  Building2,
  Calendar,
  ChartNoAxesCombined,
  CircleHelp,
  Clipboard,
  Clock,
  Cloud,
  CloudSun,
  Code,
  Cog,
  Compass,
  Copy,
  Cpu,
  Crosshair,
  Database,
  DollarSign,
  Download,
  Edit,
  Eye,
  FileCheck2,
  FileCode,
  FileEdit,
  FileText,
  FolderOpen,
  GitBranch,
  GitFork,
  Glasses,
  Globe,
  GraduationCap,
  HardDrive,
  Hash,
  Heart,
  HeartPulse,
  ImageIcon,
  Key,
  Layers,
  Layers3,
  LibraryBig,
  Lightbulb,
  Link,
  ListChecks,
  ListOrdered,
  Lock,
  Mail,
  Map,
  Megaphone,
  MessageSquare,
  MessagesSquare,
  Microscope,
  Minus,
  MousePointer2,
  Navigation,
  Network,
  Newspaper,
  NotebookPen,
  PackagePlus,
  Phone,
  PieChart,
  Plus,
  Radar,
  RefreshCw,
  Route,
  Scale,
  ScrollText,
  Search,
  Send,
  Server,
  Settings,
  Shield,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Star,
  StickyNote,
  Tag,
  Target,
  Terminal,
  TrainFront,
  Trash2,
  Twitter,
  Upload,
  UserRoundCog,
  Users,
  Volume2,
  Webhook,
  Wifi,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const ICON_PALETTE: Record<string, LucideIcon> = {
  Wrench,
  StickyNote,
  HardDrive,
  Terminal,
  Globe,
  Brain,
  Code,
  FileText,
  Target,
  Users,
  BookOpen,
  Briefcase,
  ListChecks,
  Settings,
  NotebookPen,
  Twitter,
  Mail,
  Calendar,
  GitBranch,
  Compass,
  SlidersHorizontal,
  ScrollText,
  Star,
  MessageSquare,
  MessagesSquare,
  Crosshair,
  Microscope,
  GraduationCap,
  Heart,
  DollarSign,
  Cog,
  Search,
  Eye,
  FileEdit,
  FolderOpen,
  ImageIcon,
  AlertTriangle,
  Database,
  FileCode,
  Shield,
  Lock,
  Key,
  Zap,
  Clock,
  Tag,
  Hash,
  Link,
  Send,
  Download,
  Upload,
  RefreshCw,
  Trash2,
  Plus,
  Minus,
  Edit,
  Copy,
  Clipboard,
  Archive,
  Box,
  Layers,
  Map,
  Navigation,
  Wifi,
  Cloud,
  Server,
  Cpu,
  Activity,
  BarChart,
  PieChart,
  TrainFront,
  Smartphone,
  Webhook,
  Megaphone,
  GitFork,
  FileCheck2,
  Radar,
  Volume2,
  BrainCircuit,
  HeartPulse,
  Sparkles,
  CloudSun,
  ArchiveRestore,
  Network,
  ArrowUpToLine,
  ArrowDownToLine,
  LibraryBig,
  Route,
  Newspaper,
  MousePointer2,
  PackagePlus,
  Bug,
  Glasses,
  ChartNoAxesCombined,
  CircleHelp,
  Phone,
  Badge,
  Building2,
  Scale,
  UserRoundCog,
  Workflow,
  ListOrdered,
  Layers3,
  Lightbulb,
};

export const ICON_PALETTE_NAMES = Object.keys(ICON_PALETTE);

/**
 * Canonical Session Window icon assignments.
 *
 * Every registered tool namespace and compatibility alias has a distinct icon.
 * Legacy namespaces remain explicit because historical sessions still render them.
 */
export const TOOL_ICON_MAP: Record<string, string> = {
  ui: "MousePointer2",
  scratch: "StickyNote",
  files: "HardDrive",
  shell: "Terminal",
  npm_dependencies: "PackagePlus",
  web: "Globe",
  memory: "Brain",
  railway: "TrainFront",
  sentry: "Bug",
  monday: "ClipboardList",
  meta: "Glasses",
  expo: "Smartphone",
  settings: "SlidersHorizontal",
  code: "Code",
  docx: "FileText",
  business: "ChartNoAxesCombined",
  goals: "Target",
  question: "CircleHelp",
  phone_call: "Phone",
  people: "Users",
  jobs: "Badge",
  companies: "Building2",
  library: "BookOpen",
  work: "Briefcase",
  tasks: "ListChecks",
  system: "Settings",
  issues: "AlertTriangle",
  hooks: "Webhook",
  notion: "NotebookPen",
  gmail: "Mail",
  content: "Megaphone",
  meetings: "Calendar",
  git: "GitBranch",
  scenarios: "GitFork",
  decisions: "Scale",
  exec: "UserRoundCog",
  theses: "FileCheck2",
  news: "Newspaper",
  pronunciation: "Volume2",
  rules: "ScrollText",
  orient: "Compass",
  session: "MessageSquare",
  router: "Route",
  plan: "Map",
  workflows: "Workflow",
  agendas: "ListOrdered",
  skills: "GraduationCap",
  cognition: "BrainCircuit",
  finance: "DollarSign",
  images: "ImageIcon",
  timers: "Clock",
  health: "HeartPulse",
  weather: "CloudSun",
  tools: "Wrench",
  backup: "ArchiveRestore",
  indexed_content: "LibraryBig",
  platforms: "Layers3",

  // Compatibility aliases advertised by the registry.
  projects: "FolderOpen",
  observations: "Eye",
  observation: "Lightbulb",
  create: "FileEdit",

  // Legacy namespaces preserved for historical Session Window steps.
  capabilities: "Cog",
  twitter: "Twitter",
  strategy: "Navigation",
  priorities: "Star",
  converse: "MessagesSquare",
  intentions: "Crosshair",
  observe: "Microscope",
  landscape: "Radar",
  message_sibling: "Network",
  message_parent: "ArrowUpToLine",
  message_child: "ArrowDownToLine",
};

function getToolIconByKeyword(name: string): string {
  if (name.includes("search") || name.includes("find") || name.includes("query")) return "Search";
  if (name.includes("file") || name.includes("document")) return "FileText";
  if (name.includes("user") || name.includes("person") || name.includes("contact")) return "Users";
  if (name.includes("create") || name.includes("add") || name.includes("write")) return "Plus";
  if (name.includes("delete") || name.includes("remove")) return "Trash2";
  if (name.includes("update") || name.includes("edit")) return "Edit";
  if (name.includes("list") || name.includes("get")) return "ListChecks";
  return "Wrench";
}

export function resolveToolIconName(toolName: string, overrides?: Record<string, string>): string {
  const name = toolName.toLowerCase();
  if (overrides && overrides[name]) return overrides[name];
  const direct = TOOL_ICON_MAP[name];
  if (direct) return direct;
  return getToolIconByKeyword(name);
}

export function resolveToolIcon(toolName: string, overrides?: Record<string, string>): LucideIcon {
  const iconName = resolveToolIconName(toolName, overrides);
  return ICON_PALETTE[iconName] || Wrench;
}
