import {
  Wrench,
  StickyNote,
  HardDrive,
  Terminal,
  Globe,
  Brain,
  Code,
  FileText,
  Target,
  Users,
  BookOpen,
  Briefcase,
  ListChecks,
  Settings,
  NotebookPen,
  Twitter,
  Mail,
  Calendar,
  GitBranch,
  Compass,
  SlidersHorizontal,
  ScrollText,
  Star,
  MessageSquare,
  MessagesSquare,
  Crosshair,
  Microscope,
  GraduationCap,
  Heart,
  DollarSign,
  Cog,
  Search,
  Eye,
  FileEdit,
  FolderOpen,
  ImageIcon,
  AlertTriangle,
  Database,
  FileCode,
  Shield,
  Lock,
  Key,
  Zap,
  Clock,
  Tag,
  Hash,
  Link,
  Send,
  Download,
  Upload,
  RefreshCw,
  Trash2,
  Plus,
  Minus,
  Edit,
  Copy,
  Clipboard,
  Archive,
  Box,
  Layers,
  Map,
  Navigation,
  Wifi,
  Cloud,
  Server,
  Cpu,
  Activity,
  BarChart,
  PieChart,
  TrainFront,
  Smartphone,
  Webhook,
  Megaphone,
  GitFork,
  FileCheck2,
  Radar,
  Volume2,
  BrainCircuit,
  HeartPulse,
  Sparkles,
  CloudSun,
  ArchiveRestore,
  Network,
  ArrowUpToLine,
  ArrowDownToLine,
  LibraryBig,
  type LucideIcon,
} from "lucide-react";

export const ICON_PALETTE: Record<string, LucideIcon> = {
  Wrench,
  StickyNote,
  HardDrive,
  Terminal,
  Globe,
  Brain,
  Code,
  FileText,
  Target,
  Users,
  BookOpen,
  Briefcase,
  ListChecks,
  Settings,
  NotebookPen,
  Twitter,
  Mail,
  Calendar,
  GitBranch,
  Compass,
  SlidersHorizontal,
  ScrollText,
  Star,
  MessageSquare,
  MessagesSquare,
  Crosshair,
  Microscope,
  GraduationCap,
  Heart,
  DollarSign,
  Cog,
  Search,
  Eye,
  FileEdit,
  FolderOpen,
  ImageIcon,
  AlertTriangle,
  Database,
  FileCode,
  Shield,
  Lock,
  Key,
  Zap,
  Clock,
  Tag,
  Hash,
  Link,
  Send,
  Download,
  Upload,
  RefreshCw,
  Trash2,
  Plus,
  Minus,
  Edit,
  Copy,
  Clipboard,
  Archive,
  Box,
  Layers,
  Map,
  Navigation,
  Wifi,
  Cloud,
  Server,
  Cpu,
  Activity,
  BarChart,
  PieChart,
  TrainFront,
  Smartphone,
  Webhook,
  Megaphone,
  GitFork,
  FileCheck2,
  Radar,
  Volume2,
  BrainCircuit,
  HeartPulse,
  Sparkles,
  CloudSun,
  ArchiveRestore,
  Network,
  ArrowUpToLine,
  ArrowDownToLine,
  LibraryBig,
};

export const ICON_PALETTE_NAMES = Object.keys(ICON_PALETTE);

export const TOOL_ICON_MAP: Record<string, string> = {
  scratch: "StickyNote",
  files: "HardDrive",
  shell: "Terminal",
  web: "Globe",
  memory: "Brain",
  code: "Code",
  docx: "FileText",
  goals: "Target",
  people: "Users",
  library: "BookOpen",
  work: "Briefcase",
  tasks: "ListChecks",
  system: "Settings",
  notion: "NotebookPen",
  twitter: "Twitter",
  gmail: "Mail",
  meetings: "Calendar",
  git: "GitBranch",
  strategy: "Compass",
  preferences: "SlidersHorizontal",
  rules: "ScrollText",
  priorities: "Star",
  session: "MessageSquare",
  question: "MessageSquare",
  converse: "MessagesSquare",
  intentions: "Crosshair",
  router: "Route",
  skills: "GraduationCap",
  beliefs: "Heart",
  finance: "DollarSign",
  capabilities: "Cog",
  railway: "TrainFront",
  expo: "Smartphone",
  settings: "SlidersHorizontal",
  hooks: "Webhook",
  content: "Megaphone",
  decisions: "GitFork",
  theses: "FileCheck2",
  news: "Newspaper",
  landscape: "Radar",
  pronunciation: "Volume2",
  orient: "Compass",
  plan: "Map",
  cognition: "BrainCircuit",
  observe: "Eye",
  timers: "Clock",
  health: "HeartPulse",

  weather: "CloudSun",
  tools: "Wrench",
  backup: "ArchiveRestore",
  message_sibling: "Network",
  message_parent: "ArrowUpToLine",
  message_child: "ArrowDownToLine",
  indexed_content: "LibraryBig",
};

export function getToolIconByKeyword(name: string): string {
  if (name.includes("image") || name.includes("vision") || name.includes("analyze_image")) return "ImageIcon";
  if (name.includes("search") || name.includes("find") || name.includes("grep")) return "Search";
  if (name.includes("read") || name.includes("view") || name.includes("cat")) return "Eye";
  if (name.includes("write") || name.includes("edit") || name.includes("create") || name.includes("update")) return "FileEdit";
  if (name.includes("exec") || name.includes("run") || name.includes("shell") || name.includes("bash") || name.includes("command")) return "Terminal";
  if (name.includes("web") || name.includes("fetch") || name.includes("http") || name.includes("curl") || name.includes("browse")) return "Globe";
  if (name.includes("list") || name.includes("dir") || name.includes("ls") || name.includes("folder")) return "FolderOpen";
  if (name.includes("code") || name.includes("compile") || name.includes("lint")) return "Code";
  return "Wrench";
}

export function resolveToolIconName(toolName: string, overrides?: Record<string, string>): string {
  const name = toolName.toLowerCase();
  if (overrides && overrides[name]) return overrides[name];
  const direct = TOOL_ICON_MAP[name];
  if (direct) return direct;
  return getToolIconByKeyword(name);
}

export function resolveToolIcon(toolName: string, overrides?: Record<string, string>): LucideIcon {
  const iconName = resolveToolIconName(toolName, overrides);
  return ICON_PALETTE[iconName] || Wrench;
}
