CREATE TABLE IF NOT EXISTS waitlist_applications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  position BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  email TEXT NOT NULL UNIQUE CHECK (email = lower(trim(email))),
  role TEXT NOT NULL CHECK (role IN ('founder', 'executive', 'investor', 'coach', 'creator', 'other')),
  needs TEXT[] NOT NULL CHECK (cardinality(needs) BETWEEN 1 AND 3),
  readiness TEXT NOT NULL CHECK (readiness IN ('ready', 'possible', 'lower_cost', 'curious')),
  source TEXT NOT NULL DEFAULT 'direct',
  attribution JSONB NOT NULL DEFAULT '{}'::jsonb,
  status TEXT NOT NULL DEFAULT 'waiting' CHECK (status IN ('waiting', 'reviewing', 'invited', 'deferred', 'declined')),
  confirmation_email_status TEXT NOT NULL DEFAULT 'pending' CHECK (confirmation_email_status IN ('pending', 'accepted', 'failed')),
  confirmation_email_provider_id TEXT,
  confirmation_email_error TEXT,
  confirmation_email_sent_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_waitlist_applications_status_position ON waitlist_applications(status, position);
CREATE INDEX IF NOT EXISTS idx_waitlist_applications_created_at ON waitlist_applications(created_at DESC);
