-- Historical no-op.
-- This migration briefly added bundle_defaults_version for a source-owned defaults
-- rollout. Persona bundles are persisted data, so runtime code does not read or
-- write that marker. Existing databases may retain the harmless extra column;
-- fresh databases intentionally receive no rollout state.
