import { useMemo, useState } from "react";
import { CalendarPlus, ChevronRight, Loader2, Plus, Trash2 } from "lucide-react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { BusinessPageHeader } from "@/components/business/business-page-header";
import { HierarchySearchInput } from "@/components/hierarchy-search-input";
import { HierarchySectionHeader } from "@/components/hierarchy-section-header";
import { ProfileTreeRow } from "@/components/profile-tree-row";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useSelectedBusiness } from "@/hooks/use-selected-business";
import { useToast } from "@/hooks/use-toast";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { JOB_TEAMS, type JobRole } from "@shared/models/job-roles";
import type { BusinessHiringProjection, BusinessHiringSlot } from "@shared/models/business-hiring";

function money(value: number): string { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value); }
function monthInputValue(value: string | null): string { return value ?? ""; }
function SlotRow({ slot, role, businessId }: { slot: BusinessHiringSlot; role: JobRole; businessId: string }) {
  const { toast } = useToast();
  const invalidate = () => queryClient.invalidateQueries({ queryKey: ["/api/business/hiring", businessId] });
  const update = useMutation({ mutationFn: async (plannedStartMonth: string | null) => (await apiRequest("PATCH", `/api/business/hiring/slots/${slot.id}`, { businessId, ...(plannedStartMonth ? { plannedStartMonth } : { clearFields: ["plannedStartMonth"] }), idempotencyKey: `ui-update-${slot.id}-${Date.now()}` })).json(), onSuccess: invalidate, onError: (error: Error) => toast({ title: "Could not update opening", description: error.message, variant: "destructive" }) });
  const cancel = useMutation({ mutationFn: async () => (await apiRequest("DELETE", `/api/business/hiring/slots/${slot.id}?businessId=${encodeURIComponent(businessId)}`)).json(), onSuccess: invalidate, onError: (error: Error) => toast({ title: "Could not cancel opening", description: error.message, variant: "destructive" }) });
  return <ProfileTreeRow label={slot.plannedStartMonth ? `${slot.plannedStartMonth} start` : "Unplanned opening"} icon={<ChevronRight className="h-3.5 w-3.5" />} hasValue showEmpty mobileLayout="inline" menuContent={<button type="button" className="flex items-center gap-2 text-destructive" onClick={() => cancel.mutate()}><Trash2 className="h-3.5 w-3.5" />Cancel opening</button>}>
    <div className="flex items-center gap-2"><span className="text-xs text-muted-foreground">{role.title} · approved {slot.approvalMonth}</span><Input type="month" className="h-8 w-36" value={monthInputValue(slot.plannedStartMonth)} onChange={(event) => update.mutate(event.target.value || null)} aria-label={`Planned start for ${role.title}`} /></div>
  </ProfileTreeRow>;
}
function NewSlot({ roles, businessId, onDone }: { roles: JobRole[]; businessId: string; onDone: () => void }) {
  const { toast } = useToast(); const [roleId, setRoleId] = useState(roles[0]?.id ?? ""); const [approvalMonth, setApprovalMonth] = useState(""); const [plannedStartMonth, setPlannedStartMonth] = useState("");
  const create = useMutation({ mutationFn: async () => (await apiRequest("POST", "/api/business/hiring/slots", { businessId, roleId, approvalMonth, plannedStartMonth: plannedStartMonth || null, idempotencyKey: `ui-create-${businessId}-${roleId}-${approvalMonth}-${plannedStartMonth}` })).json(), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["/api/business/hiring", businessId] }); onDone(); }, onError: (error: Error) => toast({ title: "Could not add opening", description: error.message, variant: "destructive" }) });
  return <div className="space-y-3 border-b border-border/20 px-2 py-3"><Select value={roleId} onValueChange={setRoleId}><SelectTrigger aria-label="Role"><SelectValue placeholder="Choose role" /></SelectTrigger><SelectContent>{roles.map((role) => <SelectItem key={role.id} value={role.id}>{role.title}</SelectItem>)}</SelectContent></Select><div className="grid grid-cols-1 gap-2 sm:grid-cols-2"><label className="space-y-1 text-sm"><span className="text-muted-foreground">Approval month</span><Input type="month" value={approvalMonth} onChange={(event) => setApprovalMonth(event.target.value)} /></label><label className="space-y-1 text-sm"><span className="text-muted-foreground">Planned start</span><Input type="month" value={plannedStartMonth} min={approvalMonth || undefined} onChange={(event) => setPlannedStartMonth(event.target.value)} /></label></div><div className="flex justify-end gap-2"><Button variant="ghost" size="sm" onClick={onDone}>Cancel</Button><Button size="sm" disabled={!roleId || !approvalMonth || create.isPending} onClick={() => create.mutate()}>{create.isPending && <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" />}Add Opening</Button></div></div>;
}
export default function BusinessHiringPage() {
  const { businesses, selectedId, setSelectedId } = useSelectedBusiness(); const [query, setQuery] = useState(""); const [creating, setCreating] = useState(false);
  const { data, isLoading, error, refetch } = useQuery<BusinessHiringProjection>({ queryKey: ["/api/business/hiring", selectedId], enabled: Boolean(selectedId), queryFn: async () => (await apiRequest("GET", `/api/business/hiring?businessId=${encodeURIComponent(selectedId ?? "")}`)).json() });
  const roleById = useMemo(() => new Map((data?.roles ?? []).map((role) => [role.id, role])), [data?.roles]);
  const grouped = useMemo(() => JOB_TEAMS.map((team) => ({ team, roles: (data?.roles ?? []).filter((role) => role.team === team && `${role.title} ${role.description}`.toLowerCase().includes(query.toLowerCase()) && (data?.slots ?? []).some((slot) => slot.roleId === role.id && slot.status === "approved")) })).filter((group) => group.roles.length), [data, query]);
  if (!selectedId) return <div className="w-full p-4 text-sm text-muted-foreground">Select a Business to plan hiring.</div>;
  if (isLoading) return <div className="flex h-full items-center justify-center"><Loader2 className="h-5 w-5 animate-spin text-muted-foreground" /></div>;
  if (error || !data) return <div className="w-full p-4 text-sm text-destructive">Hiring plan unavailable. <button className="text-cta" onClick={() => void refetch()}>Try again</button></div>;
  return <div className="w-full space-y-4 overflow-y-auto p-4" data-testid="business-hiring-page"><BusinessPageHeader page="Hiring" businesses={businesses} selectedId={selectedId} onSelect={setSelectedId} /><div className="flex flex-wrap items-center gap-2"><HierarchySearchInput value={query} onChange={setQuery} ariaLabel="Search hiring roles" inputTestId="input-search-hiring" clearTestId="button-clear-hiring-search" />{creating ? null : <Button className="bg-cta text-cta-foreground" onClick={() => setCreating(true)}><Plus className="mr-1.5 h-3.5 w-3.5" />Add Opening</Button>}</div>{creating && <NewSlot roles={data.roles} businessId={selectedId} onDone={() => setCreating(false)} />}<div className="overflow-x-auto border-y border-border/20"><div className="min-w-[980px]"><div className="grid grid-cols-[13rem_repeat(18,minmax(4.2rem,1fr))] border-b border-border/20 text-xs text-muted-foreground"><div className="p-2">Role / opening</div>{data.months.map((month) => <div key={month.calendarMonth} className="border-l border-border/20 p-2 text-center"><div>{month.label}</div><div className="text-2xs">{month.quarterLabel}</div></div>)}</div>{grouped.map(({ team, roles }) => <section key={team}><HierarchySectionHeader>{team}</HierarchySectionHeader>{roles.map((role) => <div key={role.id} className="grid grid-cols-[13rem_repeat(18,minmax(4.2rem,1fr))] border-b border-border/10"><div className="p-2 text-sm">{role.title}<div className="text-xs text-muted-foreground">{money(role.annualSalaryMin)}–{money(role.annualSalaryMax)}</div>{data.slots.filter((slot) => slot.roleId === role.id && slot.status === "approved").map((slot) => <SlotRow key={slot.id} slot={slot} role={role} businessId={selectedId} />)}</div>{data.months.map((month) => <div key={month.calendarMonth} className="border-l border-border/10 p-2 text-center text-sm text-muted-foreground">{data.slots.filter((slot) => slot.roleId === role.id && slot.status === "approved" && slot.plannedStartMonth && slot.plannedStartMonth <= month.calendarMonth).length || "·"}</div>)}</div>)}</section>)}<div className="grid grid-cols-[13rem_repeat(18,minmax(4.2rem,1fr))] border-t border-border/30 text-sm font-medium"><div className="p-2">Cumulative headcount / staff OpEx</div>{data.months.map((month) => <div key={month.calendarMonth} className="border-l border-border/20 p-2 text-center"><div>{month.headcount}</div><div className="text-xs text-muted-foreground">{money(month.staffOpex)}</div></div>)}</div></div></div>{data.unresolvedLegacyRoleIds.length > 0 && <div className="text-sm text-muted-foreground">Some legacy openings reference Roles no longer visible. They remain in the model as unresolved compatibility evidence.</div>}</div>;
}
