// ─── Core definition (spec §1.1, §3.3) ─────────────────────────────────────
// The single non-installable Core. Owns the substrate that stays coherent
// across every product shape plus the client routes, navigation, widgets,
// actions, and connector cards that are NOT inside one of the seven Mod
// product boundaries. Contribution IDs are prefixed `core.` — validation
// forbids any Mod from claiming that namespace or overriding a Core route/action.

import type { CoreDefinition } from "@shared/models/mod-registry";
import {
  clientRoute,
  dashboardHeatmap,
  integration,
  nav,
  widget,
} from "./contribution-builders";
import { actionsForOwner } from "./action-catalog";

export const CORE_VERSION = "1.0.0";

export const coreDefinition: CoreDefinition = {
  key: "core",
  version: CORE_VERSION,
  name: "Mantra Core",
  description:
    "The always-present substrate: Agent, Memory, Library, Automation, identity, permissions, integration custody, references, search, notifications, audit, and the Mod runtime.",
  capabilities: [
    "agent",
    "memory",
    "library",
    "automation",
    "identity",
    "integration-custody",
    "references",
    "search",
    "notifications",
    "audit",
    "ui-composition",
  ],
  contributions: {
    clientRoutes: [
      clientRoute("core.route.home", "/home", "home"),
      clientRoute("core.route.session", "/session", "session"),
      clientRoute("core.route.brain", "/brain", "brain"),
      clientRoute("core.route.personas", "/personas", "personas"),
      clientRoute("core.route.agendas", "/agendas", "agendas"),
      clientRoute("core.route.skills", "/skills", "skills"),
      clientRoute("core.route.templates", "/templates", "templates"),
      clientRoute("core.route.system", "/system", "system", { requiredPermissions: ["system:read"] }),
      clientRoute("core.route.logs", "/logs", "logs"),
      clientRoute("core.route.dashboard", "/dashboard", "dashboard", { requiredPermissions: ["system:read"] }),
      clientRoute("core.route.memory", "/memory", "memory"),
      clientRoute("core.route.tags", "/tags", "tags"),
      clientRoute("core.route.create", "/create", "create"),
      clientRoute("core.route.email", "/email", "comms"),
      clientRoute("core.route.orientation", "/orientation", "orientation"),
      clientRoute("core.route.news", "/news", "news"),
      clientRoute("core.route.recipient-recap", "/meeting-recap/:token", "recipient-recap"),
      clientRoute("core.route.timers", "/timers", "timers"),
      clientRoute("core.route.brain-timers", "/brain/timers", "timers"),
      clientRoute("core.route.integrations", "/integrations", "integrations"),
      clientRoute("core.route.integrations-provider", "/integrations/:provider", "integrations"),
      clientRoute("core.route.profile", "/profile", "profile"),
      clientRoute("core.route.zero", "/zero", "zero"),
      clientRoute("core.route.interface-preview", "/interface-preview", "interface-preview"),
      clientRoute("core.route.dev-orb", "/dev/orb", "dev-orb", { requiredPermissions: ["system:read"] }),
      clientRoute("core.route.library", "/library", "library"),
      clientRoute("core.route.info", "/info", "library"),
      clientRoute("core.route.files", "/files", "files"),
      clientRoute("core.route.audiences", "/audiences", "audiences", { requiredPermissions: ["system:read"] }),
      clientRoute("core.route.campaigns", "/campaigns", "campaigns", { requiredPermissions: ["system:read"] }),
      clientRoute("core.route.account", "/account", "user-details"),
      clientRoute("core.route.vaults", "/vaults", "vaults"),
      clientRoute("core.route.teams", "/teams", "teams"),
      clientRoute("core.route.decisions", "/decisions", "decisions"),
      clientRoute("core.route.metrics", "/tools/metrics", "business-metrics"),
      clientRoute("core.route.kpis", "/tools/kpis", "business-kpis"),
      clientRoute("core.route.performance", "/performance", "performance-screen", { requiredPermissions: ["system:read"] }),
    ],
    navigation: [
      // Tools
      nav("core.nav.home", "Tools", "Home", "Home", "navigation.home.open", "core.route.home", 1),
      nav("core.nav.dashboard", "Tools", "Dashboard", "Gauge", "navigation.dashboard.open", "core.route.dashboard", 2, { requiredPermissions: ["system:read"] }),
      nav("core.nav.news", "Tools", "News", "Newspaper", "navigation.news.open", "core.route.news", 3),
      nav("core.nav.email", "Tools", "Email", "Mail", "navigation.email.open", "core.route.email", 4),
      nav("core.nav.library", "Tools", "Library", "BookOpen", "navigation.library.open", "core.route.library", 5),
      nav("core.nav.files", "Tools", "Files", "HardDrive", "navigation.files.open", "core.route.files", 6),
      // Automation
      nav("core.nav.agendas", "Automation", "Agendas", "ClipboardList", "navigation.agendas.open", "core.route.agendas", 1),
      nav("core.nav.skills", "Automation", "Skills", "Lightbulb", "navigation.skills.open", "core.route.skills", 2),
      nav("core.nav.templates", "Automation", "Templates", "FileStack", "navigation.templates.open", "core.route.templates", 3),
      nav("core.nav.plans", "Automation", "Plans", "FileText", "navigation.plans.open", "core.route.brain", 4),
      nav("core.nav.hooks", "Automation", "Hooks", "GitBranch", "navigation.hooks.open", "core.route.system", 5, { requiredPermissions: ["system:read"] }),
      nav("core.nav.timers", "Automation", "Timers", "Clock", "navigation.timers.open", "core.route.system", 6, { requiredPermissions: ["system:read"] }),
      // Agent
      nav("core.nav.orientation", "Agent", "Orientation", "Globe", "navigation.orientation.open", "core.route.orientation", 1),
      nav("core.nav.persona", "Agent", "Persona", "User", "navigation.persona.open", "core.route.personas", 2),
      nav("core.nav.emotion", "Agent", "Emotion", "Heart", "navigation.emotion.open", "core.route.brain", 3),
      // Memory
      nav("core.nav.memory-layers", "Memory", "Layers", "DatabaseZap", "navigation.memoryLayers.open", "core.route.memory", 1),
      nav("core.nav.memory-graph", "Memory", "Graph", "Share2", "navigation.memoryGraph.open", "core.route.memory", 2),
      nav("core.nav.memory-journal", "Memory", "Journal", "ScrollText", "navigation.memoryJournal.open", "core.route.memory", 3),
      nav("core.nav.tags", "Memory", "Tags", "Tags", "navigation.tags.open", "core.route.tags", 4),
      // Tools
      nav("core.nav.metrics", "Tools", "Metrics", "Activity", "navigation.metrics.open", "core.route.metrics", 7),
      nav("core.nav.kpis", "Tools", "KPIs", "Gauge", "navigation.kpis.open", "core.route.kpis", 8),
      nav("core.nav.performance", "System", "Performance", "Gauge", "navigation.performance.open", "core.route.performance", 9, { requiredPermissions: ["system:read"] }),
      // System

      nav("core.nav.logs", "System", "Logs", "ScrollText", "navigation.logs.open", "core.route.system", 2, { requiredPermissions: ["system:read"] }),
      nav("core.nav.events", "System", "Events", "Zap", "navigation.events.open", "core.route.system", 3, { requiredPermissions: ["system:read"] }),
      nav("core.nav.tools", "System", "Tools", "Wrench", "navigation.tools.open", "core.route.system", 4, { requiredPermissions: ["system:read"] }),
      nav("core.nav.prompts", "System", "Prompts", "FileText", "navigation.prompts.open", "core.route.system", 5, { requiredPermissions: ["build:read"] }),
      nav("core.nav.context", "System", "Context", "BrainCircuit", "navigation.context.open", "core.route.brain", 6, { requiredPermissions: ["system:read"] }),
      nav("core.nav.router", "System", "Router", "Brain", "navigation.router.open", "core.route.system", 7, { requiredPermissions: ["system:read"] }),
      nav("core.nav.cost", "System", "Cost", "DollarSign", "navigation.cost.open", "core.route.system", 9, { requiredPermissions: ["system:read"] }),
      // Admin
      nav("core.nav.audiences", "Admin", "Audiences", "Users", "navigation.audiences.open", "core.route.audiences", 1, { requiredPermissions: ["system:read"] }),
      nav("core.nav.campaigns", "Admin", "Campaigns", "Megaphone", "navigation.campaigns.open", "core.route.campaigns", 2, { requiredPermissions: ["system:read"] }),
      nav("core.nav.accounts", "Admin", "Accounts", "Building2", "navigation.accounts.open", "core.route.system", 3, { requiredPermissions: ["system:read"] }),
      nav("core.nav.agents", "Admin", "Agents", "Bot", "navigation.agents.open", "core.route.system", 4, { requiredPermissions: ["system:read"] }),
      nav("core.nav.users", "Admin", "Users", "Users", "navigation.users.open", "core.route.system", 5, { requiredPermissions: ["system:read"] }),
      nav("core.nav.vaults", "Admin", "Vaults", "Vault", "navigation.vaults.open", "core.route.vaults", 6),
      nav("core.nav.teams", "Admin", "Teams", "Users", "navigation.teams.open", "core.route.teams", 7),
      nav("core.nav.integrations", "Admin", "Integrations", "Plug", "navigation.integrations.open", "core.route.integrations", 8),
      nav("core.nav.account", "Admin", "Account", "Settings", "navigation.account.open", "core.route.account", 9),
    ],
    metricAdapters: [
      {
        kind: "metric-adapter",
        id: "core.metric-adapter.performance-browser",
        adapterKey: "performance",
        definitionKeys: ["performance-route-ready-p95", "performance-main-thread-long-task-p95"],
        viewKey: "performance.screen",
        audience: "diagnostic",
      },
      {
        kind: "metric-adapter",
        id: "core.metric-adapter.tasks",
        adapterKey: "tasks",
        definitionKeys: ["completed-tasks"],
        viewKey: "core.metrics",
        audience: "diagnostic",
      },
      {
        kind: "metric-adapter",
        id: "core.metric-adapter.interactions",
        adapterKey: "interactions",
        definitionKeys: ["opportunity-interactions"],
        viewKey: "core.metrics",
        audience: "diagnostic",
      },
      {
        kind: "metric-adapter",
        id: "core.metric-adapter.product",
        adapterKey: "product",
        definitionKeys: [
          "hours-used",
          "active-users",
          "current-users",
          "new-users",
          "accounts",
          "registered-users",
          "shipped-prs",
        ],
        viewKey: "core.metrics",
        audience: "diagnostic",
        requiredPermissions: ["users:read"],
      },
    ],
    widgets: [
      widget("core.widget.state", "home.primary", "state", "state", 1),
      widget("core.widget.inbox", "home.inbox", "inbox_item", "email", 1),
    ],
    dashboardHeatmaps: [
      dashboardHeatmap(
        "core.heatmap.opportunity_interactions",
        "opportunity_interactions",
        "Opportunity interactions",
        "Briefcase",
        10,
        "operating",
      ),
      dashboardHeatmap(
        "core.heatmap.completed_tasks",
        "completed_tasks",
        "Completed tasks",
        "ClipboardList",
        20,
        "operating",
      ),
      dashboardHeatmap(
        "core.heatmap.shipped_prs",
        "shipped_prs",
        "Shipped PRs",
        "GitBranch",
        40,
        "code",
        { requiredPermissions: ["users:read"] },
      ),
    ],
    actions: actionsForOwner("core"),
    integrations: [
      integration("core.integration.google", "google", "available", ["gmail", "calendar", "drive"], {
        label: "Google",
        iconKey: "Mail",
        route: "google",
        detailSurface: "google",
        healthField: "gmailHealthy",
        statusFields: ["google"],
        ownsTitle: true,
        audience: "primary",
        readinessKind: "oauth-account",
        oauthProvider: "google",
      }),
      integration("core.integration.box", "box", "available", ["files"], {
        label: "Box",
        iconKey: "Box",
        route: "box",
        detailSurface: "box",
        statusFields: ["box"],
        audience: "primary",
      }),
      integration("core.integration.monday", "monday", "available", ["work"], {
        label: "Monday.com",
        iconKey: "ClipboardList",
        route: "monday",
        detailSurface: "monday",
        statusFields: ["monday"],
        healthField: "mondayHealthy",
        audience: "primary",
        readinessKind: "oauth-account",
        oauthProvider: "monday",
      }),
      integration("core.integration.elevenlabs", "elevenlabs", "available", ["voice"], {
        label: "ElevenLabs",
        iconKey: "Volume2",
        route: "elevenlabs",
        detailSurface: "elevenlabs",
        statusFields: ["elevenlabs"],
        requiredPermissions: ["system:read"],
        readinessKind: "secret",
        requiredSecrets: ["ELEVENLABS_API_KEY"],
      }),
      integration("core.integration.cartesia", "cartesia", "available", ["voice"], {
        label: "Cartesia",
        iconKey: "Volume2",
        readinessKind: "secret",
        requiredSecrets: ["CARTESIA_API_KEY", "CARTESIA_VOICE_ID"],
      }),
      integration("core.integration.twilio", "twilio", "available", ["phone"], {
        label: "Twilio Phone",
        iconKey: "Phone",
        route: "twilio",
        detailSurface: "twilio",
        statusFields: ["twilio"],
        requiredPermissions: ["system:read"],
        readinessKind: "secret",
        requiredSecrets: ["TWILIO_ACCOUNT_SID", "TWILIO_AUTH_TOKEN", "TWILIO_PHONE_NUMBER"],
      }),
      integration("core.integration.deepgram", "deepgram", "available", ["speech-recognition"], {
        label: "Deepgram",
        iconKey: "Mic",
        route: "deepgram",
        detailSurface: "deepgram",
        statusFields: ["deepgram"],
        requiredPermissions: ["system:read"],
        readinessKind: "secret",
        requiredSecrets: ["DEEPGRAM_API_KEY"],
      }),
      integration("core.integration.anthropic", "anthropic", "available", ["model"], {
        label: "Anthropic",
        iconKey: "Bot",
        statusFields: ["anthropic"],
        requiredPermissions: ["system:read"],
        readinessKind: "secret",
        requiredSecrets: ["ANTHROPIC_API_KEY"],
      }),
      integration("core.integration.openai", "openai", "available", ["model", "embeddings"], {
        label: "OpenAI",
        iconKey: "Bot",
        statusFields: ["openai", "openaiSubscription"],
        requiredPermissions: ["system:read"],
        readinessKind: "secret",
        requiredSecrets: ["OPENAI_API_KEY"],
      }),
      integration("core.integration.claude-cli", "claude-cli", "available", ["model"], {
        label: "Claude Code CLI",
        iconKey: "Settings",
        statusFields: ["claudeCli"],
        requiredPermissions: ["system:read"],
        readinessKind: "secret",
        requiredSecrets: ["CLAUDE_CODE_OAUTH_TOKEN"],
      }),
      integration("core.integration.grok", "grok", "available", ["model"], {
        label: "Grok",
        iconKey: "Bot",
        statusFields: ["grokSubscription"],
        requiredPermissions: ["system:read"],
      }),
      integration("core.integration.twitter", "twitter", "available", ["social"], {
        label: "X (Twitter)",
        iconKey: "Share2",
        route: "twitter",
        detailSurface: "twitter",
        statusFields: ["twitter"],
        audience: "primary",
      }),
      integration("core.integration.brave", "brave", "available", ["web-search"], {
        label: "Brave Search",
        iconKey: "Globe",
        route: "brave",
        detailSurface: "brave",
        statusFields: ["brave"],
        requiredPermissions: ["system:read"],
        readinessKind: "secret",
        requiredAnySecrets: ["BRAVE_API_KEY", "BRAVE_SEARCH_API_KEY"],
      }),
      integration("core.integration.automation-auth", "automation-auth", "available", ["automation", "browser-session"], {
        label: "Automation Auth",
        iconKey: "Shield",
        route: "automation-auth",
        detailSurface: "automation-auth",
        statusFields: ["automationAuth"],
        requiredPermissions: ["system:read"],
      }),
      integration("core.integration.sendgrid", "sendgrid", "available", ["email-send"], {
        label: "SendGrid",
        iconKey: "Mail",
        route: "sendgrid",
        detailSurface: "sendgrid",
        statusFields: ["sendgrid"],
        requiredPermissions: ["system:read"],
        readinessKind: "secret",
        requiredSecrets: ["SENDGRID_API_KEY", "SENDGRID_FROM_EMAIL"],
      }),
      integration("core.integration.meta", "meta", "available", ["wearables"], {
        label: "Meta",
        iconKey: "Glasses",
        route: "meta",
        detailSurface: "meta",
        statusFields: ["meta"],
        requiredPermissions: ["system:read"],
      }),
      integration("core.integration.recall", "recall", "available", ["meeting-transcription"], {
        label: "Recall",
        iconKey: "Radio",
        route: "recall",
        detailSurface: "recall",
        statusFields: ["recall"],
        ownsTitle: true,
        requiredPermissions: ["system:read"],
        readinessKind: "secret",
        requiredSecrets: ["RECALL_API_KEY", "RECALL_REGION"],
      }),
      integration("core.integration.stripe", "stripe", "available", ["billing"], {
        label: "Stripe",
        iconKey: "CreditCard",
        route: "stripe",
        detailSurface: "stripe",
        statusFields: ["stripe"],
        requiredPermissions: ["system:read"],
        readinessKind: "secret",
        requiredSecrets: ["STRIPE_SECRET_KEY", "STRIPE_WEBHOOK_SECRET"],
        audience: "diagnostic",
      }),
    ],
  },
};
