/**
 * Canonical list of tables whose timestamp columns must remain `timestamptz`.
 *
 * Kept in its own side-effect-free module so it can be imported by the
 * boot-heal migration (which pulls in `server/db`) AND by lightweight unit
 * tests that should not transitively initialize the database pool.
 *
 * The list is the union of every `pgTable(...)` in `shared/schema.ts` and
 * `shared/models/*.ts` that participated in the naked->timestamptz audit
 * (2026-04-23). Tables not on this list are intentionally out of scope for
 * the boot migration.
 */
export const MANAGED_TABLES: string[] = [
  "app_secrets",
  "budget_entries",
  "budget_income_override",
  "budget_monthly_overrides",
  "calendar_event_metadata",
  "calendar_event_artifacts",
  "calendar_event_people",
  "captures",
  "code_embeddings",
  "connected_accounts",
  "content_queue",
  "debt_payments",
  "decision_links",
  "decision_updates",
  "decisions",
  "email_dismissals",
  "email_drafts",
  "email_enrichments",
  "email_messages",
  "email_sync_cursors",
  "email_sync_log",
  "email_triage_log",
  "emotional_states",
  "expense_categories",
  "financed_assets",
  "financial_goals",
  "future_cash_events",
  "gratitude_entries",
  "health_metrics",
  "income_deductions",
  "income_deposits",
  "income_sources",
  "indexed_content",
  "info_notes",

  "object_acls",

  "library_annotations",
  "library_page_links",
  "library_page_views",
  "library_pages",
  "manual_assets",
  "manual_liabilities",
  "memory_content_blocks",
  "memory_entity_links",
  "memory_entries",
  "memory_events",
  "memory_links",
  "memory_transitions",
  "merchant_category_overrides",
  "messages",
  "person_merge_aliases",
  "personas",
  "plaid_accounts",
  "plaid_holdings",
  "plaid_liabilities",
  "plaid_securities",
  "plaid_sync_cursors",
  "plaid_transactions",
  "prompt_module_versions",
  "prompt_modules",
  "recurring_expenses",
  "responsibility_runs",
  "session_tree",
  "sessions",
  "skill_failure_dismissals",
  "skill_references",
  "skill_runs",
  "skills",
  "strategy_actors",
  "strategy_artifacts",
  "strategy_assumption_links",
  "strategy_assumptions",
  "strategy_context_entries",
  "strategy_end_conditions",
  "strategy_goals",
  "strategy_move_definitions",
  "strategy_move_end_condition_effects",
  "strategy_move_instances",
  "strategy_simulation_runs",
  "strategy_states",
  "system_events",
  "system_hook_executions",
  "system_hooks",
  "system_settings",
  "tasks",
  "thoughts",
  "timers",
  "users",
  "vaults",
  "voice_session_active",
  "wellness_activities",
  "wellness_logs",
  "workspace_documents",
];
